### ISSUE TITLE
mary crash

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_ui#103]
When launching on the robot I see:

```
Invalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyFatal Python error: (pygame parachute) Segmentation Fault
[ros_mary_bridge-2] process has died [pid 15341, exit code -6, cmd /opt/ros/indigo/lib/mary_tts/marybridge.py __name:=ros_mary_bridge __log:=/home/strands/.ros/log/5ebf7682-064
1-11e6-a120-00032d26c478/ros_mary_bridge-2.log].
log file: /home/strands/.ros/log/5ebf7682-0641-11e6-a120-00032d26c478/ros_mary_bridge-2*.log
```

Launching with: `HOST_IP=192.168.0.100 DISPLAY=:0 roslaunch --wait strands_bringup strands_ui.launch mary_machine:=betty mary_machine_user:=strands`

**Comment by hawesie** [comment]
It goes away if I remove the explicit `DISPLAY` setting, but I thought that this was needed for mary.

**Comment by marc-hanheide** [comment]
Well, that display needs to exist and the strands user needs to be logged in to it. Check the value of $DISPLAY locally in the X session.

**Comment by hawesie** [comment]
Ah, the X sessions is `:1` so using that fixed it.
