### ISSUE TITLE
robot screen restriction to marathon_gui only

### ISSUE THREAD

**Issue by ToMadoRe** [strands-project/strands_ui#15]
Is there a way to set up Ubuntu to allow users/students only to access the marathon_gui? Such that students can press the help button, but are not able to close any programs on the console?

**Comment by hawesie** [comment]
We are running Firefox in fullscreen/kiosk mode such that no other buttons on the screen are visible or accessible. We have a wireless keyboard which we can use in emergencies, but normal humans can't access other controls via the touch screen.

**Comment by ToMadoRe** [comment]
okay, that should do. Thanks
