### ISSUE TITLE
marathon_gui shows Ready; display = 2

### ISSUE THREAD

**Issue by ToMadoRe** [strands-project/strands_ui#16]
Launching `HOST_IP=***.***.***.*** roslaunch marathon_touch_gui marathon_gui_dependencies.launch` and going to **_.**_.**_.**_:8090 just says: Ready; display = 2.

It was working before but then it didn't update the map any more. I tried to relaunch the marathon_gui and refresh the browser, but I only get this message.

**Comment by hawesie** [comment]
You will see this until you launch the patroller, or until the patroller triggers a GUI update (if it is already running). If you are just testing the GUI you can run the following to simulate patroller calls:

```
rosrun marathon_touch_gui demo.py 
```

If this is with an already running patroller, try kicking the bumper to generate a help dialogue ;)

**Comment by ToMadoRe** [comment]
alright, kicking the bumper helped :)

**Comment by ToMadoRe** [comment]
Is there also a way to initiate this GUI without having to kick the bumper? Just wanted to have a look at the current status of the robot from external but I only see `Ready; display = 3`. Can't kick the bumper atm.

**Comment by hawesie** [comment]
If you open the webpage to the `Ready` display _before_ running the patroller you will always see it. Alternatively you can open `http://<host_ip>:8090/index.html` and the main page will be displayed. However, this won't change when the robot bumps etc. so you should return it to a `Ready` display (i.e. `http://<host_ip>:8090/`) if you leave it after this. You should also be able to connect remotely to the same address from other machines on the same network.

**Comment by bfalacerda** [comment]
you can also use a part of https://github.com/strands-project/strands_ui/blob/master/marathon_touch_gui/scripts/demo.py

Just type python in the terminal and copy paste lines 3-7, 15 and 26. Then it will update normally to the help pages

**Comment by hawesie** [comment]
Or just run

```
rosrun marathon_touch_gui demo.py 
```

This will cycle through the screens, but leave it on the main one.
