### ISSUE TITLE
GUI no longer shows run stats

### ISSUE THREAD

**Issue by cburbridge** [strands-project/strands_ui#20]
Probably after some changes to JSON run summary, mainly time is now in seconds not a string.

**Comment by hawesie** [comment]
I thought I fixed this last night: https://github.com/strands-project/strands_ui/pull/18

Is this in your running code?

**Comment by cburbridge** [comment]
no, ill test the latest version.

**Comment by hawesie** [comment]
I can confirm that after updates everything is still working for me in sim.

**Comment by ToMadoRe** [comment]
can't see any run stats either after updating

**Comment by hawesie** [comment]
Make sure strands_ui is updated. This has been working for me for a few days now.
