### ISSUE TITLE
refactor webserver / marathon ui to extract system-neutral request/response interface

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_ui#21]

**Comment by bfalacerda** [comment]
https://github.com/strands-project/strands_msgs/pull/4

Has the service definition that the help request manager node should be using. What do you think of it @hawesie ?

**Comment by hawesie** [comment]
Looks like a good start. Do we need all those constants already?

**Comment by bfalacerda** [comment]
if we want to mimic the help asking behaviours (screen and speech) that we had in the patroller during the marathon, we do. The robot displays and says different things for each (failed_component, interaction_status) pair.

**Comment by hawesie** [comment]
Ok, cool.

**Comment by hawesie** [comment]
I think I'm going to have to prioritise this after getting all the logging updates finished, so I don't expect to be able to do this until next week at the earliest. If anyone else wants to do it instead, they can assign themselves.

**Comment by bfalacerda** [comment]
I can look into it as I'm in a good position to do it. Just a doubt: I'll implement a node that provides a help via screen service, one that provides a help via speech service, and a node that provides a help request manager service, using the services provided by the previous two. There are different dependencies involved here. Should I have a single package or one per node? In which repo to put them?

**Comment by hawesie** [comment]
One package per node as we way want to install them separately and they will have very different dependencies. I'm not sure on the repo answer, and I feel my natural answer will contradict my first answer...

**Comment by bfalacerda** [comment]
Yes, that's my problem. After some coffee time discussion with the others here, we thought of putting both the screen and speech node in strands_hri. For the manager, leave it in strands_navigation as it is supposed to be used for nav recovery only and it won't add any new dependencies to it?

**Comment by hawesie** [comment]
Agreed.

**Comment by bfalacerda** [comment]
I said strands_hri, but maybe strands_ui is better?

**Comment by hawesie** [comment]
@BFALacerda did this.
