### ISSUE TITLE
strands_webserver needs webpy rosdep

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_ui#22]
`sudo apt-get install python-webpy`

was needed before it would run on a new Ubuntu install

**Comment by lucasb-eyer** [comment]
See strands-project/rosdistro#194

**Comment by lucasb-eyer** [comment]
@marc-hanheide please close this one too.

**Comment by marc-hanheide** [comment]
Only once `python-webpy` has been added to the package.xml

**Comment by lucasb-eyer** [comment]
Ah sorry, I'm still new to the packaging part.

**Comment by marc-hanheide** [comment]
shall I re-release strands_ui or are there more PRs pending/expected?

**Comment by hawesie** [comment]
No PRs pending on my end.

**Comment by marc-hanheide** [comment]
release is on the way
