### ISSUE TITLE
[nav_help_speech] starting mary?

### ISSUE THREAD

**Issue by cdondrup** [strands-project/strands_ui#28]
I was completely unaware that this package launches mary. I think mary should be launched by one of the more general launch files because it is not only used during the navigation.

**Comment by bfalacerda** [comment]
makes sense to me

**Comment by marc-hanheide** [comment]
this is resolved, is it?

**Comment by bfalacerda** [comment]
A decision was made but no action was taken :)

https://github.com/strands-project/strands_ui/blob/hydro-devel/nav_help_speech/launch/help_speech.launch#L5

This needs to be deleted, and mary should be put in some kind of bringup launch then. Since I don't have merge permissions here, maybe @cdondrup can do it?

**Comment by cdondrup** [comment]
It's still launched by nav_help_speech and I still think it should be launched somewhere else which is independent of the navigation.

**Comment by cdondrup** [comment]
Will do.

**Comment by marc-hanheide** [comment]
Cheers

**Comment by cdondrup** [comment]
Regarding the launching of mary and also the webserver, which is launched by the `help_screen`, I would suggest to launch both of them in a `strands_ui` launch file in maybe a `strands_ui_launch` or metapackage package. That would mean we have to have an additional package but it would make it more transparent when and where the ui packages are launched in the system. 
Atm both of them are launched by the navigation but are not exclusively used by the navigation which makes it a bit counter intuitive to use.

**Comment by marc-hanheide** [comment]
or alternatively, we could have a flag for those launch files as a convenience feature to provide this "autostart" feature if wanted. But the default should be that they are started elsewhere. That said, I'm not sure we'd need another launch package, because effectively that would contain two launch scripts: one for mary, one for the the webserver. These exist anyway.

**Comment by cdondrup** [comment]
Thought more of an ui_brinup launch file which contains mary and the webserver. Starting all the uis we currently have. Then the help packages would be completely optional.
The parameter is also an idea but does not really help to make the whole system set-up more transparent. The only thing that would change is that in the navigation launch file the parameter would be set to true.
My point is, that, when I was in Vienna, had to search for 10 minutes before I found where mary is started. The whole nested launch file structure has become a bit too deep for my taste.

I'm perfectly fine having a parameter and just starting it in the navigation launch file as before because that would still make it transparent enough for a release, but I would prefer to get rid of a few launch file layers.

**Comment by marc-hanheide** [comment]
OK, convinced about reducing the levels of indirection here.

**Comment by bfalacerda** [comment]
I agree with @cdondrup . I can also add a check on the help nodes that sees if mary/webserver is running. If so, the speech/screen help node continues and registers itself as a help node, if not it just warns the user that there's no ui available and returns. This way we can keep the help nodes in the monitored navigation launch without worrying too much about things breaking when launching it without having the ui stuff running before.

**Comment by marc-hanheide** [comment]
:+1:

**Comment by cdondrup** [comment]
I like that idea. Will wait with merging #42 until that is done then.
Thanks.
