### ISSUE TITLE
Prepare for release

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_ui#37]
- [ ] separate out strands_webserver into new repo dynamic_webserver
- [x] separate out robblog into new repo robblog

**Comment by marc-hanheide** [comment]
@hawesie is this still the plan to separate out dynamic_webserver? I don't think it's needed though.

**Comment by cdondrup** [comment]
Since this only holds mary and the webserver now, I don't think so either.

**Comment by cdondrup** [comment]
Everything seems to be in order for a release now. Once @hawesie gives his OK I will proceed with the release.
Also, the webserver is still missing a license. Would that be MIT @hawesie @cburbridge ?

**Comment by cdondrup** [comment]
Since the official code freeze is tomorrow, I'll release this now to be able to release the strands_hri repo.

**Comment by cdondrup** [comment]
Cannot release for indigo. `strands_webtools` is not released for indigo yet.

**Comment by marc-hanheide** [comment]
is being build now: https://github.com/strands-project/rosdistro/pull/121 give it some time to finish

**Comment by marc-hanheide** [comment]
Done. You can go ahead

**Comment by cdondrup** [comment]
Will do. Thanks.

**Comment by cdondrup** [comment]
Released for hydro and indigo.
