### ISSUE TITLE
[pygame_managed_player] No stop function

### ISSUE THREAD

**Issue by cdondrup** [strands-project/strands_ui#81]
In order to set the priorities right, the playing of music has to be stopped. Example, I run the sound_player with prio 0.5 and the music player with prio 0.9. The music player only [pauses the song](https://github.com/strands-project/strands_ui/blob/hydro-devel/music_player/scripts/music_player_server.py#L87-L90) and doesn't stop it. This leads to the sound_player never being active because the music player is still "running" having a higher priority. 

Currently there is now stop function for the player. This would have to pe implemented for this to work.

**Comment by marc-hanheide** [comment]
So, you want a stop method? Or you want the pause and resume methods to also change the volume? Or both, I suppose?
