### ISSUE TITLE
rosbridge and web sockets setup for strands_control_ui

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_ui#97]
@marc-hanheide do you know the correct way to launch the control ui whilst also having the web ui on the robot for nav recoveries etc.? Currently when I launch the web ui it brings down the nodes on the control pc which the control ui uses, and vice versa. Do I only need one set of these nodes or different ones with different names or something else?

**Comment by marc-hanheide** [comment]
I started them in a name space, see https://github.com/strands-project/strands_deployment/blob/review_y2/review_bringup/launch/review_control_pc.launch

**Comment by hawesie** [comment]
Ah, I skimmed that file too quickly. Thanks!
