### ISSUE TITLE
Modal dialogue without close button

### ISSUE THREAD

**Issue by cdondrup** [strands-project/strands_ui#99]
@marc-hanheide I think that the modal dialogue for the webserver should not have a close button because we want to permanently overlay the current webpage when the robot is under maintenance for example. There might be cases where we want to use that to inform the user about something and leave it to them to close the box or not but when triggered to inform about system events, I think it should be possible to have a dialogue without the close button to make sure it is always visible.

I tried doing that by just repeatedly publishing to the topic with `show=True` but that works only in 50% of the cases. After closing it a few times the dialogues do not appear any more and the webpage has to be reloaded to enable them again.

**Comment by cdondrup** [comment]
Ok, the close button is now gone (thank you!) but the dialogue still closes when you click anywhere on the page. Can that be fixed as well?

Didn't notice that one before, sorry.

**Comment by marc-hanheide** [comment]
release is underway.

**Comment by cdondrup** [comment]
See comment above.

**Comment by marc-hanheide** [comment]
oh, dear... I didn't know. That needs further investigation...

**Comment by marc-hanheide** [comment]
ok... need to implement this: http://stackoverflow.com/questions/22207377/disable-click-outside-of-bootstrap-model-area-to-close-modal but I'll have to go now so it'll have to wait a bit.

**Comment by cdondrup** [comment]
That's fine. Thank you!

**Comment by marc-hanheide** [comment]
and released again, now with static dialog (can only be removed with a reload of the website, but there' nothing we can do and it irrelevant, I'd say)
